# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6345a5946f80e613904d399cb6409df02331a46c0a3c40b8faae86da7949eaca30085075cc5f387bcd7101ee331075595391e9dab68241ebeed8efe651ee879a

test:
  secret_key_base: d6abfdb1b3e6a070fd6d69703c84fff77f36318d474edb5db7d6ec79df64387ab7a33f1505e7c838c1a8b320bb787fa41c5cc06ed3054957236672000d90ce83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
